@startuml
title Ввод результата участника

(*) --> "Судья авторизуется в системе"
--> "Система отображает список назначенных дисциплин"
--> "Судья выбирает дисциплину"
--> "Система отображает список участников и форму для ввода результата"

--> "Судья вводит результат для участника"

if "Данные корректны?" then
  -left->[нет] "Вывод ошибки"
  -up-> "Коррекция данных"
  --> "Судья вводит результат для участника"
else
  -right->[да] "Судья подтверждает ввод"
  --> "Система сохраняет результат в БД"
  --> "Система автоматически пересчитывает места в дисциплине"
  --> "Обновление протокола"
  --> (*)
endif

@enduml
