@startuml
title Формирование протокола

(*) --> "Администратор запрашивает отчет"
--> "Выбор типа отчета"

if "Тип отчета?" then
  ->[По дисциплине] "Выбрать конкретную дисциплину"
  --> "Система собирает данные из Базы Данных"
else
  ->[Общий зачет] "Выбрать все дисциплины соревнования"
  --> "Система собирает данные из Базы Данных"
endif

--> "Автоматически сортирует по местам"
--> "Формирует красивый документ PDF"
--> "Администратор сохраняет или печатает"
--> (*)

@enduml
