@startuml
title Добавление нового участника на соревнование

(*) --> "Администратор авторизуется в системе"
--> "Администратор выбирает соревнование"

if Статус соревнования "Запланировано?" then
  ->[нет] "Вывод ошибки Регистрация закрыта"
  --> (*)
else
  ->[да] "Администратор ищет участника в общей базе"
  
  if "Участник найден?" then
    ->[да] "Администратор регистрирует участника на соревнование"
  else
    ->[нет] "Создание карточки нового участника"
    --> "Сохранение в общую базу"
    --> "Администратор регистрирует участника на соревнование"
  endif
  
  --> "Администратор выбирает дисциплины для участника"
  --> "Система сохраняет привязку участник-соревнование-дисциплина"
  --> (*)
endif

@enduml
